#ifndef __APP_CONFIG_H
#define __APP_CONFIG_H

#define NRF_LOG_DEFAULT_LEVEL 4
#define NRF_LOG_USES_TIMESTAMP 1
#define NRF_LOG_TIMESTAMP_DEFAULT_FREQUENCY 0
#define NRF_LOG_STR_FORMATTER_TIMESTAMP_FORMAT_ENABLED 1
#define NRF_SDH_CLOCK_LF_SRC 2
#define APP_TIMER_KEEPS_RTC_ACTIVE 1
#define WDT_ENABLED 1
//#define NRFX_WDT_ENABLED 1
//#define NRFX_WDT_CONFIG_RELOAD_VALUE 5000
#define WDT_CONFIG_RELOAD_VALUE 5000
#define NRFX_WDT_CONFIG_NO_IRQ 0
#define NRFX_WDT_CONFIG_BEHAVIOUR 1
#define NRFX_WDT_CONFIG_LOG_ENABLED 1

#endif